// Static prompt data, one record per spec item. Each record feeds a per-category
// builder that stitches it into a 150–250 word redesign prompt. Keep vocabulary
// room-agnostic ("cabinetry / primary surfaces / flooring") so the same prompt
// works for kitchens, living rooms, bedrooms, bathrooms, and offices.

export interface StyleData {
  cabinetry: string;
  surfaces: string;
  walls: string;
  flooring: string;
  seating: string;
  lighting: string;
  windowTreatment: string;
  decor: string;
  mood: string;
  atmosphere: string;
}

export interface OccasionData {
  decorations: string;
  ambient: string;
  mood: string;
}

export interface LocationData {
  palette: string;
  materials: string;
  motifs: string;
  textiles: string;
  mood: string;
}

export interface ThemeData {
  palette: string;
  materials: string;
  iconography: string;
  props: string;
  mood: string;
}

export const STYLE_DATA: Record<string, StyleData> = {
  Japandi: {
    cabinetry: 'flat-panel light oak wood cabinetry and built-ins',
    surfaces: 'butcher-block wood countertops and raw-edged oak shelves',
    walls: 'two tones — warm beige cream on the upper half and deep olive green on the lower half with a clean horizontal divide',
    flooring: 'large matte black slate tiles',
    seating: 'a simple light oak rectangular wood table with one bentwood chair and one chunky raw-wood stool',
    lighting: 'a single large round paper lantern pendant',
    windowTreatment: 'sheer white linen curtains',
    decor: 'one small abstract black brushstroke artwork in a thin frame, one small potted bonsai or sculptural plant, a few clear glass bottles',
    mood: 'Soft evening ambient lighting',
    atmosphere: 'Calm, muted, restrained atmosphere',
  },
  Scandinavian: {
    cabinetry: 'pale oak flat-panel cabinetry with slim pale-wood handles',
    surfaces: 'white quartz countertops and smooth pale-oak shelves',
    walls: 'soft white paint throughout with one accent wall in a muted pale grey',
    flooring: 'wide-plank pale oak wood flooring',
    seating: 'a pale oak dining table with molded bentwood chairs and a soft wool throw draped across one',
    lighting: 'a single white ceramic pendant with a warm bulb',
    windowTreatment: 'sheer white linen curtains in long panels',
    decor: 'one framed minimalist line drawing, a potted fiddle-leaf fig, a few woven baskets',
    mood: 'Bright overcast daylight',
    atmosphere: 'Airy, clean, cosy hygge atmosphere',
  },
  Minimalist: {
    cabinetry: 'handleless matte-white flat-panel cabinetry with concealed hardware',
    surfaces: 'honed white stone countertops and a single floating white shelf',
    walls: 'pure white plaster with no mouldings',
    flooring: 'polished micro-cement in warm grey',
    seating: 'a slim white rectangular table with two matching white tulip chairs',
    lighting: 'a single flush-mount white disc ceiling fixture',
    windowTreatment: 'no window treatment — bare glass framed in slim black metal',
    decor: 'one vase with a single sculptural branch, nothing else',
    mood: 'Even diffused daylight',
    atmosphere: 'Quiet, spacious, reductive atmosphere',
  },
  'Mid-Century': {
    cabinetry: 'walnut wood flat-panel cabinetry with slim brass tab pulls',
    surfaces: 'walnut or teak countertops and open walnut shelves',
    walls: 'warm off-white paint with one accent wall in muted burnt orange or mustard',
    flooring: 'honey-toned parquet or wide walnut wood planks',
    seating: 'an Eames-style table with splayed-leg tulip chairs and a low walnut sideboard',
    lighting: 'a Sputnik brass chandelier with frosted glass globes',
    windowTreatment: 'simple cream linen curtains on a slim walnut rod',
    decor: 'one abstract geometric print, one ceramic teardrop vase, a single potted monstera',
    mood: 'Warm late-afternoon sunlight',
    atmosphere: 'Optimistic, retro, warm atmosphere',
  },
  Industrial: {
    cabinetry: 'black powder-coated steel and reclaimed wood flat-panel cabinetry',
    surfaces: 'raw steel countertops and thick reclaimed-wood shelves on black iron brackets',
    walls: 'exposed red brick on one wall, the others in grey microcement',
    flooring: 'polished concrete with visible aggregate',
    seating: 'a thick reclaimed-wood table on a steel base with black metal Tolix chairs',
    lighting: 'caged filament-bulb pendants on black cord and a single adjustable brass wall lamp',
    windowTreatment: 'black-framed Crittall-style windows left unadorned',
    decor: 'one black-and-white industrial photograph, one bronze vessel, a rolling steel bar cart',
    mood: 'Hard-edged morning light',
    atmosphere: 'Raw, urban, structural atmosphere',
  },
  Bohemian: {
    cabinetry: 'warm rattan-fronted and aged terracotta-stained wood cabinetry with wood knobs',
    surfaces: 'terracotta tile countertops and open shelves in aged pine',
    walls: 'warm off-white with one accent wall in deep terracotta or muted clay',
    flooring: 'patterned Moroccan cement tile or layered jute rugs over warm wood',
    seating: 'a rattan peacock chair, a low wood table, a wool kilim rug, embroidered floor cushions',
    lighting: 'a woven rattan pendant with a warm bulb',
    windowTreatment: 'layered macramé panels and sheer cream curtains',
    decor: 'hanging pothos and ferns, patterned throw pillows, a small collection of ceramic vessels, a vintage rug hung on the wall',
    mood: 'Warm golden-hour light filtering through plants',
    atmosphere: 'Layered, collected, well-travelled atmosphere',
  },
  Bauhaus: {
    cabinetry: 'matte black and primary-red flat-panel cabinetry with tubular steel handles',
    surfaces: 'matte white laminate countertops and painted steel shelves',
    walls: 'white walls with one block-coloured accent in primary yellow or blue',
    flooring: 'polished concrete or matte black rubber flooring',
    seating: 'a Breuer-style cantilever chair and a white lacquered rectangular table',
    lighting: 'a metal pendant in primary red',
    windowTreatment: 'bare windows in slim steel frames',
    decor: 'one Bauhaus-era geometric print (Kandinsky or Albers), a single round black clock',
    mood: 'Clean mid-day overcast',
    atmosphere: 'Functional, geometric, didactic atmosphere',
  },
  Loft: {
    cabinetry: 'dark-stained oak floor-to-ceiling cabinetry with brass pulls',
    surfaces: 'aged wood countertops and exposed-brick wall shelving',
    walls: 'exposed red brick with one wall in warm grey plaster',
    flooring: 'wide-plank reclaimed oak flooring',
    seating: 'a chunky leather Chesterfield-style sofa and a large reclaimed-wood coffee table',
    lighting: 'black iron industrial pendants and a large arc floor lamp',
    windowTreatment: 'factory-style black-framed glazing left unadorned',
    decor: 'a large abstract canvas, a rolling-ladder bookshelf, a vintage leather armchair',
    mood: 'Warm incandescent evening light',
    atmosphere: 'Urban, collected, masculine atmosphere',
  },
  Brutalist: {
    cabinetry: 'raw-concrete flat-panel cabinetry with no visible hardware',
    surfaces: 'poured concrete countertops and exposed-concrete shelves',
    walls: 'board-marked concrete walls with visible tie-hole patterns',
    flooring: 'polished concrete with expansion grid',
    seating: 'a monolithic concrete bench or thick slab table with grey wool upholstered cubes',
    lighting: 'a single exposed industrial spotlight on a black track',
    windowTreatment: 'no window treatment — deep concrete reveals',
    decor: 'a single sculptural piece: a charred wood block or raw bronze vessel',
    mood: 'Harsh side-lit daylight with deep shadows',
    atmosphere: 'Massive, austere, monumental atmosphere',
  },
  Rustic: {
    cabinetry: 'rough-sawn reclaimed-pine cabinetry with forged iron handles',
    surfaces: 'thick butcher-block countertops and chunky open pine shelves',
    walls: 'whitewashed timber-clad walls with exposed wooden beams',
    flooring: 'wide-plank distressed oak floors',
    seating: 'a farmhouse plank table and mismatched Windsor chairs',
    lighting: 'a wrought-iron candelabra chandelier',
    windowTreatment: 'gingham or ticking-stripe curtains in cream and navy',
    decor: 'a cast-iron pot on display, a bundle of dried herbs, a framed botanical print',
    mood: 'Warm morning hearth light',
    atmosphere: 'Warm, sturdy, country-house atmosphere',
  },
  Cottagecore: {
    cabinetry: 'cream painted beadboard cabinetry with brass knobs',
    surfaces: 'warm-white marble countertops and open shelves with floral plates',
    walls: 'floral wallpaper on one wall, soft cream paint on the rest',
    flooring: 'warm honey pine floors with a braided rag rug',
    seating: 'a round pine table with painted Windsor chairs and floral seat cushions',
    lighting: 'a frosted-glass dome pendant with warm bulbs',
    windowTreatment: 'gingham curtains with lace trim',
    decor: 'a pitcher of wildflowers, a stack of linen-bound books, a vintage teapot',
    mood: 'Soft morning sunlight through dappled windows',
    atmosphere: 'Nostalgic, pastoral, cosy atmosphere',
  },
  Coastal: {
    cabinetry: 'bleached-oak or whitewashed flat-panel cabinetry with rope handles',
    surfaces: 'whitewashed driftwood countertops and open shelves with seashells',
    walls: 'pale blue or crisp white walls with horizontal tongue-and-groove panelling',
    flooring: 'wide-plank bleached oak or sandy sisal carpet',
    seating: 'a whitewashed pine table with Windsor-style chairs',
    lighting: 'a rope-wrapped pendant or glass-globe nautical fixture',
    windowTreatment: 'sheer white gauze curtains billowing in a breeze',
    decor: 'a pair of weathered oars, a driftwood mirror, coral specimens in glass',
    mood: 'Bright cool seaside midday light',
    atmosphere: 'Breezy, relaxed, seafaring atmosphere',
  },
  Organic: {
    cabinetry: 'live-edge walnut or olive wood cabinetry with hand-forged bronze pulls',
    surfaces: 'live-edge wood countertops and raw-edge open shelves',
    walls: 'clay-plaster walls in warm sand or terracotta',
    flooring: 'warm-toned limestone tile or wide plank pine',
    seating: 'a live-edge slab table with hand-thrown ceramic stools',
    lighting: 'a hand-woven paper pendant or organic ceramic pendant',
    windowTreatment: 'heavy unbleached linen curtains',
    decor: 'a large ceramic vessel, a single dried branch, a wool throw in natural cream',
    mood: 'Diffused southern afternoon light',
    atmosphere: 'Earthy, tactile, hand-crafted atmosphere',
  },
  Zen: {
    cabinetry: 'low-profile teak or bamboo flat-panel cabinetry',
    surfaces: 'honed stone countertops and a single floating teak shelf',
    walls: 'plain rice-paper or plaster walls in soft ivory',
    flooring: 'tatami-mat sections bordered by smooth grey stone',
    seating: 'a low teak table with two zaisu floor chairs and a folded linen zabuton',
    lighting: 'a single shoji paper lantern',
    windowTreatment: 'translucent shoji sliding screens',
    decor: 'one ikebana arrangement of a single branch, a ceramic tea set on a slate tray',
    mood: 'Soft even north light',
    atmosphere: 'Contemplative, quiet, disciplined atmosphere',
  },
  Tropical: {
    cabinetry: 'teak or rattan-fronted cabinetry with bamboo handles',
    surfaces: 'mango-wood countertops and open rattan shelves',
    walls: 'banana-leaf wallpaper on one wall, warm cream on the rest',
    flooring: 'honey teak planks or woven seagrass mats',
    seating: 'a rattan peacock chair, a teak planter bench, a bamboo coffee table',
    lighting: 'a large woven rattan chandelier',
    windowTreatment: 'palm-print cotton curtains with a bamboo valance',
    decor: 'lush monstera and palm plants, carved wood masks, pineapple-motif accents',
    mood: 'Bright dappled jungle light',
    atmosphere: 'Lush, exotic, resort-island atmosphere',
  },
  Classic: {
    cabinetry: 'ivory raised-panel cabinetry with polished nickel hardware',
    surfaces: 'honed white marble countertops and glass-front display shelves',
    walls: 'creamy off-white with white panelled wainscot and ornate crown moulding',
    flooring: 'wide-plank polished walnut with a classic patterned rug',
    seating: 'a mahogany dining table and upholstered cream-linen chairs',
    lighting: 'a crystal chandelier with softened bulbs',
    windowTreatment: 'floor-length silk drapes with pinch-pleat tops',
    decor: 'framed oil paintings, a polished silver tea set, a fresh rose arrangement',
    mood: 'Warm afternoon candle-like light',
    atmosphere: 'Refined, formal, timeless atmosphere',
  },
  'Art Deco': {
    cabinetry: 'glossy black-lacquer cabinetry with polished brass sunburst inlays',
    surfaces: 'black or emerald marble countertops with inlaid brass lines',
    walls: 'geometric wallpaper in gold, emerald, and black stepped patterns',
    flooring: 'herringbone parquet with black-and-gold inlay border',
    seating: 'a curved emerald-velvet banquette with gold-trimmed chairs',
    lighting: 'a fan-shaped brass and frosted-glass chandelier',
    windowTreatment: 'floor-to-ceiling velvet drapes in deep jewel tones',
    decor: 'a large sunburst mirror, bronze female figurine sculptures, a cocktail bar cart',
    mood: 'Moody evening chandelier light',
    atmosphere: 'Glamorous, jewel-box, Jazz-Age atmosphere',
  },
  Hollywood: {
    cabinetry: 'high-gloss white lacquered cabinetry with polished brass handles',
    surfaces: 'white quartz countertops with gold veining and mirrored shelves',
    walls: 'soft blush or champagne with ornate white crown moulding',
    flooring: 'polished white marble with radiant gold inlay',
    seating: 'a tufted ivory-velvet sofa, a mirrored coffee table, and a gold-legged side chair',
    lighting: 'a tiered crystal chandelier',
    windowTreatment: 'pleated ivory silk drapes',
    decor: 'a large brass-framed antique mirror, faux-fur throws, crystal decanters',
    mood: 'Soft rose-gold filtered light',
    atmosphere: 'Glamorous, dramatic, silver-screen atmosphere',
  },
  Luxury: {
    cabinetry: 'book-matched dark walnut with polished brass inlays and hidden push-to-open',
    surfaces: 'book-matched Calacatta-gold marble countertops and mirrored back shelves',
    walls: 'silk-panel wallpaper in warm champagne with gilded crown moulding',
    flooring: 'large-format polished Calacatta marble',
    seating: 'a velvet tufted high-back chair and a bronze-base stone table',
    lighting: 'a sculptural crystal and brass chandelier',
    windowTreatment: 'heavy silk drapes with gold braided tiebacks',
    decor: 'an oversized gilt-frame mirror, a bronze sculpture, a crystal decanter',
    mood: 'Warm gilt-tinted evening light',
    atmosphere: 'Opulent, hushed, five-star atmosphere',
  },
  Transitional: {
    cabinetry: 'soft greige shaker cabinetry with brushed nickel hardware',
    surfaces: 'honed quartz countertops and flush-mount wood shelves',
    walls: 'warm greige paint with simple crown moulding',
    flooring: 'wide-plank oak in a medium warm tone',
    seating: 'a linen-upholstered parsons table and slipcovered chairs',
    lighting: 'a simple drum-shade pendant in ivory linen',
    windowTreatment: 'neutral linen drapes in soft greige',
    decor: 'one large neutral abstract, a vase of eucalyptus branches',
    mood: 'Balanced diffuse daylight',
    atmosphere: 'Calm, composed, approachable atmosphere',
  },
  Colonial: {
    cabinetry: 'cream raised-panel cabinetry with aged brass knobs',
    surfaces: 'dark walnut countertops and built-in china-cabinet shelves',
    walls: 'warm cream with chair-rail moulding and wainscoting below',
    flooring: 'wide-plank aged pine or polished oak with a traditional rug',
    seating: 'a Chippendale table and matching caned chairs',
    lighting: 'a brass colonial chandelier with candle-style bulbs',
    windowTreatment: 'wooden plantation shutters and cotton pleated drapes',
    decor: 'a pair of brass candlesticks, a framed botanical print, a hand-stitched sampler',
    mood: 'Warm candle-lit evening',
    atmosphere: 'Traditional, heritage, stately atmosphere',
  },
  Eclectic: {
    cabinetry: 'mismatched painted cabinetry — one in mustard, one in deep teal — with mixed brass and ceramic knobs',
    surfaces: 'reclaimed-wood countertops with mixed glass-front and open shelves',
    walls: 'gallery wall of mismatched frames on warm white paint',
    flooring: 'a patchwork of vintage rugs over wide-plank oak',
    seating: 'a velvet mid-century sofa with rattan chairs and a Moroccan pouf',
    lighting: 'a mix of lamps: a brass arc lamp, a paper lantern, candles',
    windowTreatment: 'a bold patterned Roman shade',
    decor: 'curated collection of vintage cameras, stacked travel books, ceramic animals, framed postcards',
    mood: 'Warm mixed table-lamp light',
    atmosphere: 'Personal, curated, joyful atmosphere',
  },
  Maximalist: {
    cabinetry: 'deep emerald-green lacquer cabinetry with polished brass inlay',
    surfaces: 'veined marble countertops and open shelves loaded with books and objects',
    walls: 'floor-to-ceiling floral wallpaper in jewel tones with ornate gold trim',
    flooring: 'layered Persian and oriental rugs',
    seating: 'a ruby velvet tufted sofa, patterned armchairs, a carved wood table',
    lighting: 'a crystal chandelier plus multiple patterned table lamps',
    windowTreatment: 'heavy brocade drapes with tasseled tiebacks',
    decor: 'crowded mantelpiece, stacked antique books, gilt mirrors, multiple oil paintings, plants',
    mood: 'Warm layered incandescent light',
    atmosphere: 'Lush, indulgent, more-is-more atmosphere',
  },
  Vintage: {
    cabinetry: 'chalk-painted duck-egg-blue cabinetry with aged ceramic knobs',
    surfaces: 'butcher-block countertops and open shelves with enamelware',
    walls: 'aged cream paint with one wall of vintage rose wallpaper',
    flooring: 'wide-plank distressed oak',
    seating: 'a round pine table with a pair of mid-century bentwood chairs and gingham cushions',
    lighting: 'a milk-glass pendant or an aged brass chandelier',
    windowTreatment: 'lace-trimmed cream curtains',
    decor: 'a vintage typewriter, an old camera, a pressed-flower frame, a Bakelite radio',
    mood: 'Warm late-afternoon sun through lace',
    atmosphere: 'Nostalgic, lived-in, storybook atmosphere',
  },
  Mediterranean: {
    cabinetry: 'warm whitewashed wood cabinetry with wrought-iron handles',
    surfaces: 'warm-white travertine countertops with terracotta-tile backsplash',
    walls: 'limewashed plaster walls in warm ivory with hand-painted Delft or majolica-tile accents',
    flooring: 'warm terracotta tile flooring',
    seating: 'a solid olive-wood table with rush-seat ladderback chairs',
    lighting: 'a wrought-iron lantern chandelier with warm amber bulbs',
    windowTreatment: 'iron-framed plantation shutters left partially open',
    decor: 'a hand-painted ceramic platter, a bottle of olive oil, a sprig of fresh rosemary, a majolica bowl',
    mood: 'Warm golden afternoon light',
    atmosphere: 'Sun-drenched, rustic, hospitable atmosphere',
  },
  Greek: {
    cabinetry: 'crisp-white cabinetry with simple iron knobs',
    surfaces: 'whitewashed wood countertops and open shelves',
    walls: 'rough whitewashed plaster walls with deep cobalt-blue accents',
    flooring: 'pale stone-tile flooring bleached by the sun',
    seating: 'a weathered-white wood table with caned Cycladic stools',
    lighting: 'a simple white paper lantern',
    windowTreatment: 'blue-and-white striped cotton curtains',
    decor: 'a large blue-and-white ceramic jar, a dried olive branch, a small marble amphora',
    mood: 'Bright Aegean midday sun',
    atmosphere: 'Crisp, airy, island atmosphere',
  },
  Moroccan: {
    cabinetry: 'carved dark-wood cabinetry with hand-hammered brass fretwork handles',
    surfaces: 'inlaid zellige-tile countertops and carved-wood open shelves',
    walls: 'saffron, terracotta, or deep teal plaster with Moorish-arch alcoves',
    flooring: 'patterned zellige tile or a deep Berber rug over terracotta',
    seating: 'a low carved-wood table surrounded by floor cushions and a tufted pouf',
    lighting: 'a pierced-brass lantern pendant casting patterned shadows',
    windowTreatment: 'embroidered caftan-style curtains in rich jewel tones',
    decor: 'inlaid brass trays, a tagine, hand-stitched textiles, colourful lanterns',
    mood: 'Warm amber dusk light',
    atmosphere: 'Rich, jewel-toned, souk atmosphere',
  },
  Andalusian: {
    cabinetry: 'hand-painted white cabinetry with hand-glazed ceramic handles',
    surfaces: 'terracotta-tile countertops with azulejo-tile backsplash',
    walls: 'whitewashed plaster walls with blue-and-yellow azulejo-tile panels',
    flooring: 'warm terracotta tile floor',
    seating: 'a carved-wood farmhouse table with rush-seat chairs and a wrought-iron candelabra centrepiece',
    lighting: 'a wrought-iron candle-style chandelier',
    windowTreatment: 'iron grille window left uncurtained',
    decor: 'a hand-embroidered wool rug, a mounted ceramic plate, fresh olives in a blue bowl',
    mood: 'Warm late-morning Mediterranean light',
    atmosphere: 'Warm, tiled, Moorish-Spanish atmosphere',
  },
  'High-Tech': {
    cabinetry: 'seamless brushed-stainless-steel cabinetry with flush push-to-open',
    surfaces: 'stainless-steel countertops with hidden under-cabinet LED strips',
    walls: 'dark matte microcement walls with integrated LED strip lighting',
    flooring: 'polished microcement floor in deep charcoal',
    seating: 'a carbon-fibre chair and a black-glass table with brushed-steel base',
    lighting: 'recessed LED track lights and a hanging glass-tube pendant',
    windowTreatment: 'automated roller blinds in charcoal technical fabric',
    decor: 'a single exposed cable light, a minimalist dock, a polished steel sculpture',
    mood: 'Cool LED-tinted evening light',
    atmosphere: 'Sleek, precision-engineered, laboratory atmosphere',
  },
  Futuristic: {
    cabinetry: 'curved glossy-white lacquer cabinetry with integrated touch-open panels',
    surfaces: 'seamless glass or white solid-surface countertops with embedded LED edges',
    walls: 'curved white walls with an illuminated seam of cool-blue LED',
    flooring: 'glossy resin floor with embedded geometric LED inlay',
    seating: 'a single translucent acrylic chair and a curved white table',
    lighting: 'a floating white sphere pendant with halo glow',
    windowTreatment: 'electrochromic dimmable glass left unadorned',
    decor: 'a single illuminated sculpture, a robotic planter, a holographic-style wall display',
    mood: 'Cool blue-white ambient glow',
    atmosphere: 'Sci-fi, clinical, forward-looking atmosphere',
  },
  Postmodern: {
    cabinetry: 'bright block-colour cabinetry in clashing pink, yellow, and teal',
    surfaces: 'patterned terrazzo countertops and open shelves with playful objects',
    walls: 'stripes, squiggles, or checkered walls in bold contrasting colours',
    flooring: 'colourful terrazzo tile or a bold geometric rug',
    seating: 'a squiggle-leg Memphis table with plastic geometric chairs in primary colours',
    lighting: 'a sculptural cluster pendant in clashing hues',
    windowTreatment: 'a single bold patterned Roman shade',
    decor: 'Memphis-style objects: squiggles, zigzags, and solid geometric shapes',
    mood: 'Bright, flat, saturated light',
    atmosphere: 'Playful, ironic, Memphis-Milano atmosphere',
  },
  Steampunk: {
    cabinetry: 'riveted brass-and-copper cabinetry with exposed gear handles',
    surfaces: 'aged brass countertops and reclaimed-wood open shelves on brass-pipe supports',
    walls: 'deep aged-leather-coloured walls with exposed brass piping and riveted copper panels',
    flooring: 'wide-plank aged oak with a chequered iron-inlay border',
    seating: 'a carved-leather Chesterfield-style chair and a brass-fitted table with clockwork base',
    lighting: 'exposed Edison filament bulbs on articulated brass arms with gauges',
    windowTreatment: 'heavy oxblood-velvet curtains with brass tiebacks',
    decor: 'antique maps, brass telescopes, vintage typewriters, clockwork gears',
    mood: 'Warm amber filament glow',
    atmosphere: 'Victorian-industrial, inventor-workshop atmosphere',
  },
  'Retro 60s': {
    cabinetry: 'teak and white-laminate cabinetry with chrome arch pulls',
    surfaces: 'Formica countertops in cream or sky-blue with atomic-pattern backsplash',
    walls: 'one wall in bright mustard or turquoise, others in cream',
    flooring: 'checkered linoleum in cream-and-black or a high-pile shag rug',
    seating: 'an Eames-style table with tulip chairs and a kidney-shape side table',
    lighting: 'a Sputnik chandelier or a starburst pendant',
    windowTreatment: 'geometric-patterned curtains in teal and orange',
    decor: 'a vintage transistor radio, a lava lamp, a rotary phone, a pop-art print',
    mood: 'Warm mid-afternoon atomic-age light',
    atmosphere: 'Optimistic, space-age, 1960s atmosphere',
  },
  'Retro 70s': {
    cabinetry: 'warm orange or avocado-green laminate cabinetry with wood-grain trim',
    surfaces: 'burnt-orange tile countertops and macramé-trimmed open shelves',
    walls: 'one wall in deep mustard or burnt-sienna, others in warm cream with a geometric wallpaper accent',
    flooring: 'thick shag rug in rust or moss-green over warm wood',
    seating: 'a curved modular brown-corduroy sofa and a smoked-glass coffee table',
    lighting: 'a mushroom-shape table lamp and a coloured pendant',
    windowTreatment: 'beaded curtains or heavy floral drapes',
    decor: 'a macramé wall hanging, potted spider plants, vinyl records on shelves, a lava lamp',
    mood: 'Warm golden afternoon with amber glow',
    atmosphere: 'Earthy, groovy, 1970s atmosphere',
  },
  'Retro 80s': {
    cabinetry: 'glossy pastel cabinetry in mint, peach, and white with chrome pulls',
    surfaces: 'laminate countertops in pastel or solid black',
    walls: 'Memphis-pattern wallpaper with squiggles and confetti on one wall, glossy pastel on the rest',
    flooring: 'black-and-white checker tile or bold patterned carpet',
    seating: 'a chrome-and-glass table with pastel leather chairs',
    lighting: 'a neon wall sign and a brass arc floor lamp',
    windowTreatment: 'mini-blinds in charcoal or pastel',
    decor: 'a boombox, neon geometric art, a brass palm-tree sculpture, chrome accessories',
    mood: 'Bright neon-tinted evening',
    atmosphere: 'Bold, pastel-neon, 1980s atmosphere',
  },
  'Retro 90s': {
    cabinetry: 'oak flat-panel cabinetry with brushed-chrome bar pulls',
    surfaces: 'laminate countertops in speckled grey or forest green',
    walls: 'hunter-green or burgundy accent wall with cream on the rest and a floral border wallpaper',
    flooring: 'beige wall-to-wall carpet or polished oak planks',
    seating: 'an overstuffed floral-print sofa, a plaid armchair, and a round oak coffee table',
    lighting: 'a brass ceiling fan with frosted-glass lights and a torchiere floor lamp',
    windowTreatment: 'a swagged valance with lace sheers',
    decor: 'a stack of VHS tapes, a corded telephone, a plaid throw, a wooden duck',
    mood: 'Warm evening table-lamp glow',
    atmosphere: 'Cosy, floral-plaid, 1990s suburbs atmosphere',
  },
};

export const OCCASION_DATA: Record<string, OccasionData> = {
  Christmas: {
    decorations: 'a decorated evergreen Christmas tree with warm-white string lights and red ribbons, a pine garland draped over the mantel, red stockings, and a small wooden nativity scene',
    ambient: 'sprigs of holly and cinnamon-stick bundles, a plaid wool throw, a red velvet table runner',
    mood: 'Warm candle-light and fireplace glow',
  },
  Halloween: {
    decorations: 'carved jack-o-lantern pumpkins on the floor, a cluster of tall black candles on the table, faux cobwebs stretched across the ceiling corners',
    ambient: 'orange string lights, dried autumn leaves and black ribbons, a black raven silhouette, a few small fake tombstones',
    mood: 'Moody orange firelight with flickering shadows',
  },
  Wedding: {
    decorations: 'cascading white and ivory floral arrangements on every surface, white tulle draped across the ceiling, tall ivory pillar candles, and a table set with fine china and crystal',
    ambient: 'rose petals scattered on the floor, a "Mr & Mrs" calligraphy sign, strings of delicate fairy lights, cream ribbons tied to chair backs',
    mood: 'Soft candle-lit dusk with warm fairy lights',
  },
  "New Year's Eve": {
    decorations: 'gold and silver foil balloon bundles, a backdrop of metallic streamers, a champagne bucket with two flutes, and a large sparkler-style signage',
    ambient: 'gold confetti strewn across the floor, a black-and-gold sequined table runner, a disco-ball accent, party hats and noisemakers',
    mood: 'Glittering mid-evening party light with reflected gold',
  },
  Birthday: {
    decorations: 'a cluster of colourful balloons in a rainbow palette, a banner reading "Happy Birthday", and a frosted cake with lit candles on a stand',
    ambient: 'paper streamers across the ceiling, confetti on the floor, party hats and paper plates',
    mood: 'Bright cheerful afternoon with cake-lit candles',
  },
  'Baby Shower': {
    decorations: 'a pastel balloon arch in pink, blue, or neutral cream, a "Baby on the way" banner, a table with a small frosted cake and tiny plush toys',
    ambient: 'delicate pastel streamers, folded baby blankets, a stack of wrapped gifts in soft wrapping paper',
    mood: 'Soft daylight with gentle pastel pink-and-blue glow',
  },
  'Gender Reveal Party': {
    decorations: 'a dramatic balloon arch in 50/50 pink and blue, a large balloon filled with reveal confetti, and a cake with pink-or-blue interior',
    ambient: 'pink and blue streamers, a large "HE OR SHE" banner, a table stacked with gender-reveal props',
    mood: 'Bright afternoon with anticipatory pink-and-blue lighting',
  },
  Graduation: {
    decorations: 'a cluster of black, gold, and school-colour balloons, a mortarboard-cap cake, a framed diploma on display, and a "Congrats Grad" banner',
    ambient: 'streamers in school colours, a photo-backdrop of the grad, confetti on the floor',
    mood: 'Bright celebratory mid-afternoon light',
  },
  Housewarming: {
    decorations: 'a "Welcome Home" banner, a fresh floral centerpiece, a platter of charcuterie, and wrapped housewarming gifts',
    ambient: 'a soft garland over the doorway, small potted plants as favours, a decorated guestbook',
    mood: 'Warm golden-hour welcome light',
  },
  Engagement: {
    decorations: 'cascading pink-and-white floral arrangements, a large "She Said Yes" calligraphy sign, a ring-box accent on the table',
    ambient: 'tulle draped across the ceiling, tea lights in glass votives, a champagne display',
    mood: 'Soft pink-gold dusk candlelight',
  },
  Anniversary: {
    decorations: 'a bouquet of deep-red roses on every surface, a pair of golden candles, a framed wedding photograph, a silk table runner',
    ambient: 'soft rose petals on the floor, a vintage-style music player, a bottle of wine with two glasses',
    mood: 'Warm candle-lit intimate evening',
  },
  "Valentine's Day": {
    decorations: 'a bouquet of red roses, heart-shaped balloons, a heart garland, and a small box of chocolates on the table',
    ambient: 'red and pink rose petals scattered, tealights in red glass, a pair of champagne flutes',
    mood: 'Soft warm rose-tinted evening light',
  },
  'Lunar New Year': {
    decorations: 'red lanterns hung from the ceiling, gold-foil "good fortune" calligraphy wall hangings, peach-blossom branches in vases, and a display of mandarin oranges',
    ambient: 'red and gold paper chains, small golden fish ornaments, a dragon-dance mask on the wall',
    mood: 'Warm red-gold firelight',
  },
  Easter: {
    decorations: 'pastel Easter-egg arrangements in woven baskets, a floral wreath of tulips and daffodils, a bunny figurine on the table',
    ambient: 'pastel ribbons draped across chairs, fresh spring flowers in bud vases, colourful foil-wrapped chocolate eggs',
    mood: 'Bright pastel spring-morning light',
  },
  Thanksgiving: {
    decorations: 'a cornucopia overflowing with pumpkins, gourds, and wheat sheaves, tall amber candles, and a burlap table runner',
    ambient: 'scattered dried autumn leaves, pine cones, a "Grateful" wood sign',
    mood: 'Warm late-autumn afternoon with golden candlelight',
  },
  Diwali: {
    decorations: 'rows of terracotta diya oil lamps with lit flames, marigold garlands draped along doorways, a colourful rangoli pattern on the floor',
    ambient: 'strings of golden fairy lights, brass bells, a floral centerpiece of marigolds and jasmine',
    mood: 'Glowing warm amber lantern light',
  },
  Ramadan: {
    decorations: 'a Moroccan lantern chandelier, crescent-moon and star wall hangings, dates and figs on a brass tray, a date-palm branch in a vase',
    ambient: 'warm-glowing strings of small star lamps, embroidered cushions on the floor, a prayer rug',
    mood: 'Warm dusk amber-light atmosphere',
  },
  Eid: {
    decorations: 'a cluster of gold and white balloons, an "Eid Mubarak" calligraphy banner, a table with traditional sweets and dates',
    ambient: 'strings of crescent-moon lights, fresh roses, henna-patterned textiles',
    mood: 'Warm festive evening with golden-amber light',
  },
  Hanukkah: {
    decorations: 'a lit menorah on the centre of the mantel, blue-and-white string lights, a Star-of-David centerpiece, and a bowl of gelt coins',
    ambient: 'blue and silver ribbons, a plate of sufganiyot, a dreidel collection',
    mood: 'Warm menorah-candle glow at dusk',
  },
  'Super Bowl': {
    decorations: 'a large television playing a football game as the focal point, team-colour balloon bundles, a football-shape centerpiece on the coffee table',
    ambient: 'team pennants on the walls, a tray of nachos and wings, beer bottles, foam fingers',
    mood: 'Bright game-day living-room light with TV glow',
  },
  'World Cup Final': {
    decorations: 'a large television playing the match, multi-national flags strung across the room, a football-shape centerpiece',
    ambient: 'a team-jersey draped over the sofa, a tray of snacks and beers, small football memorabilia',
    mood: 'Bright evening fan-gathering light',
  },
  '4th of July': {
    decorations: 'red, white, and blue balloon clusters, a large American-flag bunting draped across one wall, star-spangled streamers, and a patriotic centerpiece',
    ambient: 'mini flags in a vase, a red-white-blue table runner, sparklers in a decorative holder',
    mood: 'Bright summer-evening golden light',
  },
  "St. Patrick's Day": {
    decorations: 'green balloon clusters, a shamrock garland, a pot of "gold" wrapped chocolate coins, and a "Happy St. Patrick\'s Day" sign',
    ambient: 'green streamers, mini leprechaun hats, green-tinted tea-light candles',
    mood: 'Bright emerald-tinted afternoon light',
  },
  'Cinco de Mayo': {
    decorations: 'colourful papel picado banners across the ceiling, a sombrero on the wall, a cactus centerpiece, maracas and mini piñatas',
    ambient: 'a serape-striped table runner, cactus plants in terracotta pots, lime slices in a bowl',
    mood: 'Warm festive late-afternoon sun',
  },
  'Pride Month': {
    decorations: 'a large rainbow flag draped across one wall, a rainbow balloon arch, pride pennants strung across the ceiling',
    ambient: 'rainbow confetti, a "Love is Love" calligraphy sign, rainbow-iced cookies',
    mood: 'Bright joyful mid-day celebratory light',
  },
};

export const LOCATION_DATA: Record<string, LocationData> = {
  Parisian: {
    palette: 'ivory cream, aged gold, soft dove grey, and muted rose',
    materials: 'painted boiserie wall panels, herringbone oak parquet, and white Carrara marble surfaces',
    motifs: 'a gilt-framed mirror over the mantel, a zinc-topped café table, chandelier drops',
    textiles: 'toile de Jouy cushions, a velvet bergere chair, silk pleated drapes',
    mood: 'Soft afternoon light through tall French windows',
  },
  Tuscan: {
    palette: 'warm terracotta, olive green, sun-bleached ochre, and cream plaster',
    materials: 'rough terracotta tile floor, limewashed plaster walls, and aged olive-wood surfaces',
    motifs: 'a hand-painted majolica platter, a bunch of dried lavender, a pottery olive-oil jar, a wrought-iron candelabra',
    textiles: 'heavy unbleached linen drapes and a dried-flower wreath',
    mood: 'Warm golden Tuscan afternoon light',
  },
  Tokyo: {
    palette: 'neutral ink-grey, paper-white, warm cedar, and accent red',
    materials: 'sliding shoji paper screens, tatami-mat inserts, and hinoki-cypress wood surfaces',
    motifs: 'a bonsai on a low platform, a hanging kakejiku scroll, a tea-ceremony tray, a wind chime',
    textiles: 'an indigo noren curtain, simple cotton zabuton cushions',
    mood: 'Calm diffuse paper-filtered light',
  },
  Californian: {
    palette: 'warm sand, terracotta, dusty sage, and sun-bleached white',
    materials: 'wide-plank bleached oak floors, rough limewashed walls, and live-edge wood surfaces',
    motifs: 'a large hanging macrame, a cluster of cacti and succulents, a woven seagrass mat, a ceramic vessel collection',
    textiles: 'layered cream and terracotta wool throws, a jute rug',
    mood: 'Bright dry afternoon sun',
  },
  African: {
    palette: 'warm ochre, deep terracotta, and charcoal black with aged brass accents',
    materials: 'hand-carved dark wood surfaces and woven-grass textures',
    motifs: 'carved wooden masks, woven reed baskets on the wall, a tribal-pattern textile',
    textiles: 'kuba cloth cushions, a mudcloth throw, a hand-woven rug',
    mood: 'Warm earth-toned afternoon light',
  },
  American: {
    palette: 'rustic oak, navy blue, muted red, and warm cream',
    materials: 'reclaimed oak surfaces, warm brass fittings, and painted wood details',
    motifs: 'a framed vintage American-flag art, a stack of Americana magazines',
    textiles: 'a woven denim throw, plaid cotton pillows, a braided rag rug',
    mood: 'Warm front-porch afternoon light',
  },
  Australian: {
    palette: 'eucalyptus green, warm sandstone, and coral pink',
    materials: 'warm honey-toned wood and sandstone accent surfaces',
    motifs: 'a framed gum-leaf botanical print, a surfboard leaning in a corner, a woven aboriginal-inspired textile',
    textiles: 'a linen throw in dusty sage, woven palm mats',
    mood: 'Bright coastal dry-bush daylight',
  },
  Belgian: {
    palette: 'dove grey, putty, warm cream, and pale oak',
    materials: 'pale limed oak surfaces, antique weathered timber, and raw linen',
    motifs: 'an antique Belgian farm-table centrepiece, a weathered stone urn with branches',
    textiles: 'chunky Belgian-linen drapes and slipcovered cushions',
    mood: 'Soft misty grey daylight',
  },
  Arabian: {
    palette: 'jewel saffron, deep teal, ruby red, and polished brass',
    materials: 'carved wood lattice mashrabiya panels and patterned Islamic tilework',
    motifs: 'Arabic calligraphy wall art, a hanging shisha lantern, a brass tray of dates',
    textiles: 'silk jewel-tone cushions and a deep Persian rug',
    mood: 'Warm lantern-lit evening',
  },
  Moroccan: {
    palette: 'warm terracotta, deep cobalt, saffron, and polished brass',
    materials: 'zellige-tile surfaces, tadelakt plaster walls, and carved-wood accents',
    motifs: 'Moorish-arch alcoves, pierced-brass lanterns, a hanging kilim',
    textiles: 'a Berber wool rug, embroidered floor cushions, a wool throw',
    mood: 'Warm amber souk-dusk light',
  },
  Provence: {
    palette: 'lavender, wheat, dusty blue, and cream',
    materials: 'rough-sawn oak timber, limewashed plaster, and hand-painted ceramic accents',
    motifs: 'a bouquet of dried lavender, a framed botanical print, a vintage French spice rack, a pressed-herb arrangement',
    textiles: 'toile-print curtains and a gingham cotton runner',
    mood: 'Warm Provence-sunset afternoon',
  },
  Alpine: {
    palette: 'warm honey pine, cream wool, and deep forest green',
    materials: 'rough-hewn pine log surfaces, stone hearth accents, and felted-wool textures',
    motifs: 'a pair of mounted antlers, a stack of split firewood, a cowbell, a framed alpine landscape',
    textiles: 'thick plaid wool blankets and a shearling throw',
    mood: 'Warm firelight chalet glow',
  },
  'New York': {
    palette: 'deep oak, brass, exposed-brick red, and charcoal',
    materials: 'dark oak panelling, exposed red brick, and polished brass fittings',
    motifs: 'a large sash window facing a skyline, a framed subway-map print, a rolling bookshelf ladder',
    textiles: 'a heavy velvet throw, a Persian rug in deep oxblood',
    mood: 'Warm evening brownstone parlour light',
  },
  'New Zealand': {
    palette: 'earthy green, sea blue, and raw sheepskin cream',
    materials: 'warm-toned sustainable timber and natural wool textures',
    motifs: 'a pounamu jade accent, a framed fern-leaf print, a driftwood sculpture',
    textiles: 'a thick sheepskin rug and wool-loomed throws',
    mood: 'Cool fjord-morning coastal light',
  },
  London: {
    palette: 'heritage navy, oxblood, forest green, and polished brass',
    materials: 'dark oak panelling, Chesterfield leather, and brass fittings',
    motifs: 'a framed London Underground map, a stack of hardcover books, a globe on a stand, Victorian moulding',
    textiles: 'a tartan throw, a heavy velvet cushion, a Persian rug',
    mood: 'Warm evening library lamp light',
  },
  Lisbon: {
    palette: 'azulejo blue-and-white, terracotta, pastel yellow, and warm cream',
    materials: 'hand-painted azulejo tile accents and warm stucco walls',
    motifs: 'a patterned azulejo tile panel, a pastel-painted door accent, a framed tram photograph',
    textiles: 'a cotton striped runner and palm-print curtains',
    mood: 'Warm Atlantic afternoon light',
  },
  Venetian: {
    palette: 'rich damask red, gilded gold, faded pastels, and aged cream',
    materials: 'gilded stucco walls, Murano-glass accents, and hand-painted chests',
    motifs: 'a Venetian-mask display, a Murano-glass chandelier, a painted folding screen',
    textiles: 'heavy damask drapes and embroidered silk cushions',
    mood: 'Warm Venetian-dusk chandelier glow',
  },
  Texan: {
    palette: 'weathered leather, cowhide tan, turquoise, and rust',
    materials: 'heavy weathered leather, wrought-iron fixtures, and rough-sawn oak surfaces',
    motifs: 'a mounted steer skull on the wall, a turquoise accent vase, a framed Western landscape, a rope accent',
    textiles: 'a cowhide rug, a Navajo-pattern wool throw',
    mood: 'Warm golden ranch afternoon',
  },
  Miami: {
    palette: 'pastel pink, deco teal, palm green, and sunset orange',
    materials: 'pastel-lacquered deco panels, terrazzo accents, and chrome fittings',
    motifs: 'a pair of pink flamingo ornaments, a palm-print wall accent, a neon script "Miami" sign',
    textiles: 'palm-print curtains and pastel velvet cushions',
    mood: 'Bright pastel beach-deco afternoon',
  },
  Mexican: {
    palette: 'bright cobalt, saffron, terracotta, and emerald',
    materials: 'hand-painted Talavera-tile accents and carved-wood surfaces',
    motifs: 'a papel-picado garland, a hand-painted catrina figurine, a framed Frida Kahlo print, a clay sun-face on the wall',
    textiles: 'a serape-striped table runner, embroidered cotton cushions',
    mood: 'Bright warm folklore-afternoon light',
  },
  Cuba: {
    palette: 'faded pastel blue, salmon pink, aged cream, and warm mahogany',
    materials: 'aged plaster walls, rattan accents, and warm mahogany surfaces',
    motifs: 'a vintage cigar-box display, a classic 1950s Cadillac illustration, a rum-bar cart, a framed Havana-street photograph',
    textiles: 'sheer cotton curtains and embroidered cushions',
    mood: 'Warm Havana-golden-hour light',
  },
  Caribbean: {
    palette: 'aqua teal, coral pink, palm green, and warm cream',
    materials: 'rattan surfaces, bleached palm-wood accents, and whitewashed plaster',
    motifs: 'a conch-shell centerpiece, a framed tropical-fish print, a palm-leaf ceiling fan, a driftwood-and-shell sculpture',
    textiles: 'a palm-print throw, sheer cotton curtains',
    mood: 'Bright turquoise-sea afternoon',
  },
  Milan: {
    palette: 'warm stone, polished brass, walnut, and emerald',
    materials: 'honed travertine surfaces, walnut veneer, and polished-brass inlays',
    motifs: 'a Gio-Ponti silhouette chair, a marble-and-brass coffee table, a framed Italian-design poster',
    textiles: 'a velvet throw and a plush mohair cushion',
    mood: 'Warm Milanese late-afternoon light',
  },
  Ryokan: {
    palette: 'soft cedar tan, paper ivory, and dark slate grey',
    materials: 'tatami-mat flooring, shoji paper screens, and hinoki-wood cypress surfaces',
    motifs: 'a low tea table, a hanging kakejiku scroll, an ikebana arrangement, a cedar soaking-tub detail',
    textiles: 'a folded cotton yukata and linen zabuton cushions',
    mood: 'Soft cedar-warmed ryokan evening',
  },
  Shanghai: {
    palette: 'lacquer red, gold leaf, jade green, and deep black',
    materials: 'black-lacquered surfaces, silk panels, and carved rosewood accents',
    motifs: 'a red-lacquer carved screen, a jade-inlay sculpture, a silk calligraphy banner, a porcelain ginger-jar lamp',
    textiles: 'silk cushions and a hand-embroidered runner',
    mood: 'Warm lantern-glow Shanghai evening',
  },
  'South Korean': {
    palette: 'cedar tan, ivory, jade green, and warm charcoal',
    materials: 'hanok-style cedar columns, hanji paper walls, and warm ondol-heated floors',
    motifs: 'a traditional moon-jar ceramic, a hanging bojagi wrapping-cloth panel, a carved wooden screen',
    textiles: 'linen seat cushions and hand-loomed cotton drapes',
    mood: 'Warm ondol-heated evening glow',
  },
  'North Korean': {
    palette: 'muted grey, deep propaganda red, and pale concrete',
    materials: 'stark plaster walls, plain pine surfaces, and exposed concrete',
    motifs: 'a framed propaganda-poster-style art, a red-silk lapel-pin display, utilitarian shelving',
    textiles: 'plain cotton curtains and heavy wool drapes',
    mood: 'Stark mid-morning institutional light',
  },
  Bali: {
    palette: 'carved teak brown, emerald palm green, lotus pink, and warm cream',
    materials: 'carved dark teak surfaces, rattan panels, and rough volcanic-stone accents',
    motifs: 'a stone Buddha statue, a hanging lotus-petal chandelier, a batik-print wall hanging, a woven offering-basket',
    textiles: 'a batik throw, rattan-woven cushions',
    mood: 'Warm jungle-filtered afternoon',
  },
  Santorini: {
    palette: 'whitewashed plaster, deep cobalt blue, and aged cream',
    materials: 'rough whitewashed plaster, bleached driftwood, and blue-painted accents',
    motifs: 'a blue-painted domed-arch accent, a ceramic amphora, a string of dried chilies, a hanging rope-and-shell sculpture',
    textiles: 'blue-and-white striped cotton cushions and linen curtains',
    mood: 'Bright Aegean noon sun',
  },
  Ibiza: {
    palette: 'whitewashed adobe, caramel rattan, and bohemian pink',
    materials: 'whitewashed adobe walls, rattan-woven surfaces, and smooth-cane accents',
    motifs: 'a large macramé wall hanging, a cluster of hanging plants, a carved-wood moon-mirror, a candle-scattered alcove',
    textiles: 'sheer linen curtains and a Berber wool rug',
    mood: 'Warm dry-island dusk',
  },
  India: {
    palette: 'saffron, peacock blue, emerald, and polished brass',
    materials: 'carved wood jali screens, hand-painted ceramic accents, and brass surfaces',
    motifs: 'a hanging brass diya lamp, a block-printed cotton panel, a carved teak screen, a marigold garland accent',
    textiles: 'block-print cotton cushions and a heavily embroidered throw',
    mood: 'Warm festival-lantern evening',
  },
  Scandi: {
    palette: 'pale white, pale oak, and muted grey',
    materials: 'pale oak surfaces and soft white plaster',
    motifs: 'a framed minimalist print, a woven basket, a single potted plant',
    textiles: 'a chunky wool throw and soft linen cushions',
    mood: 'Bright overcast daylight',
  },
  Nordic: {
    palette: 'bleached oak, deep charcoal, slate grey, and icy white',
    materials: 'bleached oak surfaces, slate-stone accents, and raw wool textures',
    motifs: 'a framed fjord landscape, a sheepskin throw, a stack of split firewood, a cast-iron lantern',
    textiles: 'chunky wool throws and a reindeer-hide rug',
    mood: 'Cool fjord-sunlight morning',
  },
};

export const THEME_DATA: Record<string, ThemeData> = {
  'Harry Potter': {
    palette: 'deep emerald, burgundy, aged gold, and worn parchment cream',
    materials: 'dark oak panelling, wrought-iron fixtures, and aged-leather surfaces',
    iconography: 'a banner of the four Hogwarts house crests, framed parchment with wand-motion diagrams',
    props: 'a pile of old spellbooks, a brass telescope, a worn cauldron, a collection of glass potion bottles, a quill and parchment, mounted deer antlers',
    mood: 'Moody flickering candle- and fireplace-light, great-hall atmosphere',
  },
  Barbie: {
    palette: 'hot pink, bubble-gum pink, cream, and pops of silver and turquoise',
    materials: 'glossy pink-lacquer panels, white faux-fur textures, and pastel-pink terrazzo',
    iconography: 'a "Barbie" script neon sign, a Barbie-logo decor display',
    props: 'a pink convertible-style toy car, a rainbow heart mirror, a tiered pink cupcake display, a plush flamingo',
    mood: 'Bright saturated pink-gold afternoon',
  },
  Cyberpunk: {
    palette: 'neon magenta, electric blue, teal, acid yellow over matte black and charcoal',
    materials: 'riveted dark metal, matte charcoal walls, and polished black resin floors',
    iconography: 'illuminated Japanese-kanji signage, holographic-style projections',
    props: 'a wall of LED screens, a cyber-augmented mannequin, fibre-optic cables draped along the ceiling, a chrome motorcycle helmet',
    mood: 'Rain-soaked neon-bathed dusk with flickering signs',
  },
  'Studio Ghibli': {
    palette: 'soft pastel sky-blue, warm cream, moss green, and sunlit gold',
    materials: 'hand-painted watercolour-style walls and warm oak and linen textures',
    iconography: 'a soot-sprite cluster in a corner, a Totoro plush on a shelf, a bath-house Spirited-Away sign',
    props: 'a stack of illustrated storybooks, a teacup and kettle, a potted cluster of wildflowers, a mini Catbus',
    mood: 'Soft watercolour afternoon light filtering through leaves',
  },
  'Star Wars (The Mandalorian)': {
    palette: 'desert sand, gunmetal grey, warm bronze, and deep black',
    materials: 'brushed steel panels, weathered concrete walls, and heavy aged-leather surfaces',
    iconography: 'a silver Mandalorian helmet on a pedestal, a Din Djarin banner, a floating-pod-chair detail',
    props: 'a wall-mounted blaster rifle, a small Grogu plush in a floating pod, Beskar-steel wall art, a desert-cactus specimen',
    mood: 'Golden desert-sunset-through-windows atmosphere',
  },
  Dune: {
    palette: 'desert beige, bronze, deep gold, and inky black',
    materials: 'rough sandstone, brushed brass, and heavy black-fabric drapes',
    iconography: 'a Fremen crysknife replica, Harkonnen black-and-orange insignia',
    props: 'a brass stillsuit on a stand, Spice-orange melange decor, an Arrakis-map wall hanging',
    mood: 'Warm dust-filtered desert noon',
  },
  'Peaky Blinders': {
    palette: 'soot-black, oxblood, brass, and heavy-storm-cloud grey',
    materials: 'soot-stained brick, tarnished brass, and aged leather',
    iconography: 'a newsboy cap on a hook, a straight-razor display',
    props: 'a whisky bottle and two tumblers, a gramophone, a pack of cards, a vintage revolver',
    mood: 'Smoky-yellow-amber Birmingham-pub interior lighting',
  },
  'Game of Thrones': {
    palette: 'stone grey, oxblood, ice blue, and weathered gold',
    materials: 'rough stone walls, dark oak beams, and iron fixtures',
    iconography: 'the Iron Throne silhouette, house sigils (wolf, dragon, lion), dragon-egg replicas',
    props: 'a dire-wolf pelt, a hanging antler chandelier, fur-lined Westerosi cloaks, a crossed-sword mount',
    mood: 'Cold grey-north stone-castle daylight',
  },
  'The Lord of the Rings': {
    palette: 'moss green, warm earthen brown, aged gold, and cream',
    materials: 'hobbit-hole round-arched doorways, hand-carved oak, and warm flagstone',
    iconography: 'the Ring inscription carved on the mantel, Gandalf\'s staff against a wall',
    props: 'a cluttered wood bookshelf, a hobbit-style armchair, a pipe-and-tobacco set, Elvish scroll parchments',
    mood: 'Warm hobbit-hearth fireplace light',
  },
  Friends: {
    palette: 'warm terracotta-orange, teal, and cream',
    materials: 'second-hand mismatched wood furniture and 1990s-apartment textures',
    iconography: 'the Central Perk coffee-shop sign, a yellow frame around the peephole',
    props: 'a cream three-seat sofa, a coffee table with magazines, a foosball table, a "Joey" script on a wall',
    mood: 'Warm Central-Perk evening lamp light',
  },
  'The Matrix': {
    palette: 'green-tinted black, rain-soaked grey, and digital emerald',
    materials: 'dark vinyl, latex-like black leather, and brushed steel',
    iconography: 'falling-code "green rain" projected on a wall',
    props: 'a red-and-blue pill display, a black trench coat on a stand, mirrored chrome sunglasses, an old rotary phone',
    mood: 'Green-tinted rainy nightclub light',
  },
  'Stranger Things': {
    palette: 'deep purple, neon red, forest green, and Upside-Down shadows',
    materials: 'wood-panel 1980s walls, shag carpets, and warm vinyl surfaces',
    iconography: 'a Christmas-light alphabet wall spelling "RUN", an Eggo-waffle box, a Dungeons & Dragons board',
    props: 'a Scoops Ahoy uniform hat, stacked bicycles, a wall of Polaroids, a walkie-talkie',
    mood: 'Moody basement-glow-with-string-lights atmosphere',
  },
  Avatar: {
    palette: 'bioluminescent turquoise, deep jungle green, and neon pink',
    materials: 'organic curved plant-forms, sparkling bio-lume accents, and tribal-woven textures',
    iconography: 'the Tree of Souls as a focal piece, large glowing floral branches',
    props: 'a bow-and-arrow hung on a wall, a floating-island-model decor, glowing tendril vines',
    mood: 'Luminous Pandora-night with bioluminescent accents',
  },
  'Breaking Bad': {
    palette: 'dust-beige, methylamine pale blue, brown, and rust',
    materials: 'industrial chemistry lab textures — stainless steel, latex, and glass beakers',
    iconography: 'a gas mask on a hook, a yellow hazmat suit on a stand',
    props: 'chemistry beakers, a stack of blue-glass crystals, a "Los Pollos Hermanos" sign',
    mood: 'Dusty amber Albuquerque sunset with laboratory fluorescence',
  },
  'The Simpsons': {
    palette: 'bright yellow, blue, red, and cartoon cream',
    materials: 'flat cartoon-primary textures with outlined illustrated edges',
    iconography: 'a pink Lard Lad donut display, a Krusty-the-Clown poster, Duff-beer cans',
    props: 'an orange three-seater sofa, a Bart-Simpson skateboard, a TV showing "Itchy and Scratchy"',
    mood: 'Bright flat cartoon noon',
  },
  Futurama: {
    palette: 'retro-sci-fi teal, hot pink, neon green, and chrome',
    materials: 'chrome-plated 1950s-retro-futuristic curves and glossy white plastic',
    iconography: 'a Planet Express ship model, a Bender-the-robot-shaped lamp',
    props: 'a chrome-sphere jukebox, a head-in-a-jar preservation, a Slurm-can pyramid',
    mood: 'Retro-neon 31st-century daylight',
  },
  'Rick and Morty': {
    palette: 'neon-green portal, acid yellow, and garage dust',
    materials: 'cluttered science-garage workbench, grime and duct-tape, portal-gun chrome',
    iconography: 'a neon-green swirling portal wall projection',
    props: 'a portal gun on a shelf, a Meeseeks box, a Plumbus, scattered bolts and wires, a mini ship',
    mood: 'Bright interdimensional green-neon light',
  },
  SpongeBob: {
    palette: 'bubble-gum pink, aqua blue, bright yellow, and coral-sunset orange',
    materials: 'pineapple-textured walls, sand-coloured flooring, and cartoon-style surfaces',
    iconography: 'a pineapple doorway cutout, a Krusty-Krab menu sign',
    props: 'a giant pineapple lamp, a jellyfish net, a Krabby-Patty plush, bubble wands',
    mood: 'Bright underwater-Bikini-Bottom noon',
  },
  'Blade Runner 2049': {
    palette: 'orange dust-haze, deep teal, amber neon, and brushed copper',
    materials: 'brutalist concrete, dust-caked steel, and flickering holographic walls',
    iconography: 'a large pink holographic Joi projection, Wallace Corporation signage',
    props: 'a Spinner-car model, a paper origami unicorn, an L.A.-2049 skyline poster',
    mood: 'Orange-dust-apocalyptic twilight with neon',
  },
  Interstellar: {
    palette: 'corn-yellow, spacecraft grey, and cosmic indigo',
    materials: 'NASA-era aluminium hardware, concrete walls, and navy plastic surfaces',
    iconography: 'a tesseract-model wall art, an Endurance spacecraft model',
    props: 'a cornfield print, Cooper\'s ranger helmet, a TARS robot figure, a blackboard with equations',
    mood: 'Dusty rural-sunset Americana into space-black night',
  },
  'The Great Gatsby': {
    palette: 'champagne, black-and-gold, oyster pearl, and emerald',
    materials: 'mirrored art-deco panels, polished black marble, and silk drapes',
    iconography: 'a "West Egg" mansion photograph, a green-light-across-the-bay painting',
    props: 'a crystal decanter set, an ostrich-feather fan, an art-deco sunburst mirror, a golden flapper-era gramophone',
    mood: 'Jazz-age chandelier-and-candle sparkle',
  },
  'The Godfather': {
    palette: 'oxblood, dark espresso, cream, and muted olive',
    materials: 'dark-walnut panelling, a red Persian rug, and aged-leather surfaces',
    iconography: 'the Corleone family photograph, a cannoli and orange bowl, a cat on a chair',
    props: 'a mahogany desk with a leather chair, a bottle of chianti, an antique rotary phone, opera-poster art',
    mood: 'Moody espresso-toned Sicilian parlour light',
  },
  Titanic: {
    palette: 'navy, cream, polished mahogany, and silver',
    materials: 'polished mahogany panelling, brass fittings, and silk drapes',
    iconography: 'a silver-framed porthole mirror, a nude-charcoal sketch on an easel',
    props: 'a gramophone, a heart-of-the-ocean necklace, a brass ship wheel, an Edwardian-style dresser',
    mood: 'Opulent Edwardian chandelier-and-brass-lamp light',
  },
  'Fight Club': {
    palette: 'dusty plaster-white, soap-bar pink, yellow grime, and shadow-black',
    materials: 'peeling old wallpaper, bare bulbs, and warehouse concrete',
    iconography: 'a Project-Mayhem soap bar as centerpiece, "First rule of Fight Club" graffiti',
    props: 'a thrifted couch, a pair of boxing gloves, a vintage typewriter, a lye-soap pile',
    mood: 'Stark bare-bulb basement flicker',
  },
  'Joker / Batman': {
    palette: 'Gotham-purple, acid-green, crimson, and deep black',
    materials: 'art-deco Wayne-manor carved panels or grimy asylum concrete',
    iconography: 'a "HA HA HA" graffiti wall detail, a crossed-bat silhouette',
    props: 'a playing-card deck fanned across the table, a purple trench coat, a batarang on the mantel, a clown mask',
    mood: 'Moody Gotham-rain-at-night green-neon flicker',
  },
  'The Martian': {
    palette: 'rust-red Mars soil, silver spacecraft, and orange jumpsuit',
    materials: 'Martian-habitat plastic panels, botany-grow-light surfaces, and duct-tape accents',
    iconography: 'a large "Mars" wall map, rocky-red terrain photos',
    props: 'a potato-grow box, a NASA jumpsuit, a Rover model, a GoPro camera',
    mood: 'Warm orange-Mars-sunset with cold habitat fluorescence',
  },
  'Wes Anderson': {
    palette: 'powder-pink, mustard, warm peach, and Wes-yellow',
    materials: 'symmetrical patterned wallpaper, old-hotel brass, and velvet upholstery',
    iconography: 'a "Grand Budapest Hotel" sign detail, a hot-air-balloon miniature',
    props: 'a vintage typewriter, a stack of suitcases, a curated set of perfectly-centred objects, a fox terrarium',
    mood: 'Perfectly symmetrical pastel midday',
  },
  Minecraft: {
    palette: 'pixel-grass green, dirt brown, stone grey, and TNT red',
    materials: 'cubic blocky-textured walls, wood-plank blocky flooring, and stone-block surfaces',
    iconography: 'a Creeper-face wall-tile pattern, a pickaxe mounted on the wall',
    props: 'an enchanting-table model, a chest, a torch sconce, a pixel-sheep plush',
    mood: 'Bright block-world noon with square sun',
  },
  Pixar: {
    palette: 'Up-balloon rainbow, Toy-Story-cloud blue-and-cream, Monsters-Inc. purple',
    materials: 'soft cartoon-plush finishes with rounded edges',
    iconography: 'a cluster of Up-balloons floating in the corner, a Pixar desk lamp, Luxo-Jr. on a shelf',
    props: 'a Buzz Lightyear figure, a Nemo fish-tank, a Remy-rat toy, a Cars license plate',
    mood: 'Warm animated-golden-hour light',
  },
  'Tim Burton': {
    palette: 'black-and-white stripes, blood-red, oxblood, and silver',
    materials: 'twisted-branch gothic carved wood, haunted-mansion damask wallpaper',
    iconography: 'a Jack-Skellington silhouette, a spiral-hill landscape',
    props: 'a Beetlejuice-striped suit on display, a raven-feather bouquet, a cursed pocket-watch, skeletal-hand candelabras',
    mood: 'Moonlit midnight with warm amber candles',
  },
  'Anime/Manga': {
    palette: 'vibrant pink, electric blue, sakura pink, and black ink',
    materials: 'bold-ink outlined cartoon surfaces, onomatopoeia speech-bubble wallpaper accents',
    iconography: 'a large anime poster, rows of manga-book spines, action-line effect wallpaper',
    props: 'a cosplay costume on a mannequin, a samurai katana replica, plush chibi characters, a Japanese-style bento on a shelf',
    mood: 'Vivid sakura-afternoon cherry-blossom light',
  },
};

export function buildStylePromptFromData(name: string, data: StyleData): string {
  return `Transform this interior into a ${name} style. Keep the same room layout, window position, and camera angle. Replace existing cabinetry and built-ins with ${data.cabinetry}. Replace primary surfaces (countertops, tabletops, shelving) with ${data.surfaces}. Paint walls in ${data.walls}. Replace flooring with ${data.flooring}. Replace primary furniture with ${data.seating}. Replace overhead lighting with ${data.lighting}. Add ${data.windowTreatment}. Remove all clutter, papers, magnets, loose objects, and random decorations. Add minimal decor: ${data.decor}. ${data.mood}. ${data.atmosphere}. Photorealistic interior photography.`;
}

export function buildOccasionPromptFromData(
  name: string,
  data: OccasionData,
): string {
  return `Decorate this existing room for ${name}. Preserve the existing furniture, walls, floors, cabinetry, windows, and camera angle — do not replace or remove them. Add ${data.decorations}. Add ${data.ambient}. ${data.mood}. Photorealistic interior photography.`;
}

export function buildLocationPromptFromData(
  name: string,
  data: LocationData,
): string {
  return `Infuse this room with ${name} aesthetic. Keep the same room layout, window position, and camera angle. Shift the palette to ${data.palette}. Replace primary surfaces and finishes with ${data.materials}. Add characteristic elements: ${data.motifs}. Add ${data.textiles}. Remove generic clutter while preserving the room's architectural bones. ${data.mood}. Photorealistic interior photography.`;
}

export function buildThemePromptFromData(name: string, data: ThemeData): string {
  return `Transform this room into a ${name}-themed space. Keep the same room layout, window position, and camera angle. Shift the palette to ${data.palette}. Replace primary surfaces with ${data.materials}. Add iconography: ${data.iconography}. Add characteristic props: ${data.props}. Remove unrelated clutter while preserving the room's architectural bones. ${data.mood}. Photorealistic interior photography.`;
}
