import {
  LegalPageLayout,
  SupportEmailLink,
} from '@/components/home/LegalPageLayout';

export const metadata = {
  title: 'Terms & Conditions · Envisio',
  description:
    'The terms that govern your use of Envisio, an AI-powered interior redesign tool.',
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms & Conditions" lastUpdated="April 19, 2026">
      <p>
        These Terms govern your access to and use of Envisio
        (&ldquo;<strong>Envisio</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;,
        &ldquo;<strong>us</strong>&rdquo;), an AI-powered interior redesign
        service. By creating an account or using the service you agree to
        these Terms. If you do not agree, do not use Envisio.
      </p>

      <h2>1. The Service</h2>
      <p>
        Envisio lets you upload a photo of a room and generate AI-based
        redesigns in various styles, themes, and lighting conditions. Image
        generation is performed by third-party AI providers on our behalf.
        Output quality, accuracy, and availability are not guaranteed.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You need an account to use Envisio. Authentication is handled by
        Clerk. You are responsible for the confidentiality of your
        credentials and for all activity under your account. You must be at
        least 13 years old (or the minimum age in your jurisdiction) to
        create an account.
      </p>

      <h2>3. Your Content</h2>
      <p>
        You retain ownership of the images you upload and the prompts you
        write (&ldquo;<strong>Your Content</strong>&rdquo;). You grant us a
        limited, worldwide, non-exclusive license to store, process, and
        transmit Your Content solely to operate the service (for example,
        sending your photo to our AI provider to generate a redesign, or
        displaying your history inside the app).
      </p>
      <p>
        You represent that you have the right to upload every image you
        submit, and that Your Content does not infringe anyone&rsquo;s
        rights, contain illegal material, or violate these Terms.
      </p>

      <h2>4. AI-Generated Outputs</h2>
      <p>
        Images produced by Envisio are generated by a probabilistic AI model.
        You keep whatever rights the law grants you in the outputs; we do
        not claim ownership of your generations. You acknowledge that (a)
        similar inputs may produce similar outputs for other users, (b)
        AI-generated content&rsquo;s copyright status varies by jurisdiction,
        and (c) generations may occasionally contain artifacts or
        inaccuracies.
      </p>

      <h2>5. Tokens &amp; Plans</h2>
      <p>
        Image generations are metered using tokens. Each new account
        receives a free starting balance. You can purchase additional tokens
        via a one-time plan (<strong>Custom</strong>) or a monthly
        subscription (<strong>Standard</strong> or <strong>Professional</strong>).
        Subscription tokens reset at each billing cycle and do not carry
        over. Tokens have no cash value and are non-transferable.
      </p>
      <p>
        If a generation fails for a reason on our side (provider outage,
        model error, cancellation), we automatically refund the token to
        your balance. See our Refund Policy for details on monetary refunds.
      </p>

      <h2>6. Billing</h2>
      <p>
        Payments are processed by Paddle, who acts as the merchant of record
        and handles tax calculation, invoicing, and refunds. Subscriptions
        renew automatically at the end of each billing period until
        cancelled. You can cancel at any time from your Paddle customer
        portal; cancellation takes effect at the end of the current period.
      </p>

      <h2>7. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>upload images you do not have the right to use;</li>
        <li>
          upload or generate content that is illegal, sexualized,
          exploitative of minors, violent, harassing, discriminatory, or
          that impersonates a real person without consent;
        </li>
        <li>
          use Envisio to generate images of real identifiable individuals
          without their permission;
        </li>
        <li>
          attempt to circumvent token metering, reverse engineer the
          service, or interfere with its operation;
        </li>
        <li>
          resell the service, share an account with another person, or
          automate generations in a way that degrades the service for
          others.
        </li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate these rules and we
        may remove Your Content at our discretion.
      </p>

      <h2>8. Third-Party Services</h2>
      <p>
        Envisio relies on external providers (Clerk for auth, Vercel Blob
        for file storage, Neon for database, Replicate for image generation,
        Anthropic for conversational prompt assistance, and Paddle for
        payments). Your use of the service is also subject to their
        respective terms. We are not responsible for outages, errors, or
        policy changes originating at those providers.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        Envisio is provided on an &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; basis, without warranties of any kind, express or
        implied, including merchantability, fitness for a particular
        purpose, or non-infringement. AI outputs are not professional design
        advice; do not rely on them for construction, procurement, or
        structural decisions without consulting a qualified professional.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Envisio and its affiliates
        will not be liable for any indirect, incidental, special,
        consequential, or punitive damages, or for lost profits, revenue, or
        data. Our total aggregate liability arising out of or related to the
        service is limited to the greater of (a) the amount you paid us in
        the twelve months preceding the claim, or (b) USD 50.
      </p>

      <h2>11. Termination</h2>
      <p>
        You can stop using Envisio at any time. We may suspend or close your
        account if you violate these Terms or if required by law. On
        termination, your right to use the service ends; unused tokens may
        be forfeited.
      </p>

      <h2>12. Changes</h2>
      <p>
        We may update these Terms over time. If the change is material, we
        will notify you by email or through the app before it takes effect.
        Continued use of Envisio after an update means you accept the new
        Terms.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the jurisdiction in which
        Envisio is operated, without regard to conflict-of-law principles.
        Any dispute that cannot be resolved informally will be brought in
        the competent courts of that jurisdiction.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms? Email <SupportEmailLink />.
      </p>
    </LegalPageLayout>
  );
}
